version: "3.4"
services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    environment:
      ConnectionStrings__DefaultConnection: "Server=172.0.0.3;Port=5432;Database=admin;User ID=admin;Password=admin;Enlist=true"
    expose:
      - 5000
    depends_on:
      - postgres
  nginx:
    build: ./nginx
    ports:
      - 80:80
    environment:
      BACKENF_HOST: "app:5000"
    networks:
      app_net:
        ipv4_address: 172.30.0.2
  postgres:
    build: ./postgres
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
    networks:
      app_net:
        ipv4_address: 172.30.0.3

networks:
  app_net:
    name: app_net
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.30.0.0/24
